' Jan Schmidt Jensen

@startuml Class Diagram

class ATM{
    -accounts
    -admin
    -reserves
    +deposit()
    +withdraw()
    +showBalance()
    +transfer()
    +maintainance()
}

class Bank{
    -accounts
    -createAccount()
    +getAccountInfo()
}

class Account{
    -accountName 
    -accountNumber
    -accountBalance
    -pin
    -isLocked
    +lockAccount()
    +getBalance()
    +setBalance()
    +pinValidation()
    +updatePin()
    -hashFunction()
}

class Admin{
    -UserAdmin
    -Password
    +GetATMinfo()
    -hashFunction()
}
class GUI{
    +displayMenu()
    +requestPinCode()
    +requestAmount()
    +requestTransactionsType()
    +displayBalance()
    +displayErrors()
}
class Security{
    +encryptData
    +decryptData
    +pinValidation()
}

ATM *-* Admin
ATM *-- GUI
ATM *-- Security
Bank *- ATM
Bank *-- Account
Admin o----o Account

@enduml